#!/bin/bash

logpath="/home/chrifpa/.adnlog"
maxlen=256

post=""

for word in $@; do
	post="$post $word"
done

count=${#post}

let count-=maxlen

if [ $count -le 0 ]; then
	texapp -status="$post" > $logpath
	
	if grep -Fq "FAIL" $logpath; then
        	echo "   ...ugh, something went wrong :("
	fi
	rm $logpath

else
	echo "too long by $count :("
fi
