#!/bin/bash

ipold="/home/mrnda/Dropbox/PlainText/.igor.ip.txt"
ipcurrent=`curl icanhazip.com`

aiccu stop
sleep 10s

if [ `cat $ipold` != $ipcurrent ] 
        then
        echo $ipcurrent > $ipold
fi

aiccu start
