#!/bin/bash

USAGE="Usage: `basename $0` [-hvps]"

# Parse command line options.

out=/dev/null

while getopts hvpzm OPT; do
    case "$OPT" in
        h)
		echo $USAGE
		exit 0
		;;
        v)
		echo verbose mode
		out=/dev/stderr
		;;
        p)
		echo poking igor
		echo 'igor on' | ssh root@2001:6f8:900:f3d::2 &>$out
		;;
	z)
		echo zapping igor
		echo 'igor off' | ssh root@2001:6f8:900:f3d::2 &>$out
		;;
	m)
		mosh mrnda@2001:6f8:900:8f3d:221:ccff:fe36:d63a
		;;
        \?)
            # getopts issues an error message
            echo $USAGE >&2
            exit 1
            ;;
    esac
done

