#! /bin/sh

USAGE="Usage: `basename $0` [-hvps]"

# Parse command line options.

out=/dev/null

while getopts hvps OPT; do
    case "$OPT" in
        h)
		echo $USAGE
		exit 0
		;;
        v)
		echo verbose mode
		out=/dev/stderr
		;;
        p)
		echo poking igor
		echo 'igor on' | ssh root@2001:6f8:900:f3d::2 &>$out
		;;
	s)
		echo slapping igor
		echo 'igor off' | ssh root@2001:6f8:900:f3d::2 &>$out
		;;
        \?)
            # getopts issues an error message
            echo $USAGE >&2
            exit 1
            ;;
    esac
done

