#!/bin/bash

today=$HOME/.today
date=$(date +%Y%m%d)

if [ "$(cat $today | tr -d '\n')" != "$date" ]; then

	echo -n $date > $today
	echo $(fortune $HOME/.dotfiles/.fortunes) > $HOME/.thought
fi

echo $(cat $HOME/.thought)