#!/bin/bash

logpath="/home/chrifpa/.twlog"
maxlen=140

tweet=""

for word in $@; do
	tweet="$tweet $word"
done

count=${#tweet}

let count-=maxlen

if [ $count -le 0 ]; then
	ttytter -status="$tweet" > $logpath
	
	if grep -Fq "FAIL" $logpath; then
        	echo "   tw: ...ugh, something went wrong :("
	fi
	rm $logpath

else
	echo "tw: too long by $count :("
fi
