#!/bin/bash

# save as /bin/tw and /bin/adn

if [ $0 == "./up" ] && [ $1 == "install" ]; then
	echo installing...
	cp $(pwd)/up /bin/tw
	cp $(pwd)/up /bin/adn
else

if [ $0 == "/usr/bin/tw" ] || [ $0 == "/bin/tw" ]; then
	this=tw
	maxlen=140
	client=ttytter
else if [ $0 == "/usr/bin/adn" ] || [ $0 == "/bin/adn" ]; then
	this=adn
	maxlen=256
	client=texapp
	fi
fi

logpath="/home/$(whoami)/.${this}log"

post=""

for word in $@; do
	post="$post $word"
done

count=${#post}

let count-=maxlen

if [ $count -le 0 ]; then
	$client -status="$post" > $logpath
	
	if grep -Fqi "FAIL" $logpath; then
		echo "   $this: ...ugh, something went wrong :("
	else
		echo "$this: done."
	fi
	rm $logpath

else
	echo "$this: too long by $count :("
fi

fi
